name: dizon36
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pandas>=2.0
  - numpy>=1.25 
  - matplotlib 
  - jupyter 
  - notebook 
  - rtree
  - pyproj>=2.0
  - pyshp
  - scikit-learn
  - shapely
  - tensorflow
  - pip:
      - flopy
      - pyemu
      - pypestutils
      - vtk
      - git+https://github.com/p-ortega/mf6rtm.git@feature/externalio
